# Generated by Django 3.1.1 on 2020-09-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200915_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='cost_currency',
        ),
    ]
